/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor v4.1-1-ga49a51a

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY, UNLESS YOU KNOW WHAT YOU ARE DOING !!!!
*******************************************************************************/

#define OD_DEFINITION
#include "301/CO_ODinterface.h"
#include "OD.h"
/* 引入节点角色，使对象字典只在节点 A 中启用 B/C 心跳监控。 */
#include "canopen_node_config.h"

#if CO_VERSION_MAJOR < 4
#error This Object dictionary is compatible with CANopenNode V4.0 and above!
#endif

/*******************************************************************************
    OD data initialization of all groups
*******************************************************************************/
OD_ATTR_PERSIST_COMM OD_PERSIST_COMM_t OD_PERSIST_COMM = {
    .x1000_deviceType = 0x00000000,
    .x1005_COB_ID_SYNCMessage = 0x00000080,
    .x1006_communicationCyclePeriod = 0x00000000,
    .x1007_synchronousWindowLength = 0x00000000,
    .x1012_COB_IDTimeStampObject = 0x00000100,
    .x1014_COB_ID_EMCY = 0x00000080,
    .x1015_inhibitTimeEMCY = 0x0000,
    .x1016_consumerHeartbeatTime_sub0 = 0x08,
    /* 节点 A 监控节点 B、C，超时时间分别为 1500 ms。 */
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_A)
    .x1016_consumerHeartbeatTime = {
        CANOPEN_HEARTBEAT_CONSUMER_ENTRY(2U, CANOPEN_HEARTBEAT_CONSUMER_TIMEOUT_MS), /* 配置监控 B，Node-ID 为 2。 */
        CANOPEN_HEARTBEAT_CONSUMER_ENTRY(3U, CANOPEN_HEARTBEAT_CONSUMER_TIMEOUT_MS), /* 配置监控 C，Node-ID 为 3。 */
        0x00000000U, /* 保留监控项 3，不启用远端节点。 */
        0x00000000U, /* 保留监控项 4，不启用远端节点。 */
        0x00000000U, /* 保留监控项 5，不启用远端节点。 */
        0x00000000U, /* 保留监控项 6，不启用远端节点。 */
        0x00000000U, /* 保留监控项 7，不启用远端节点。 */
        0x00000000U  /* 保留监控项 8，不启用远端节点。 */
    },
#else
    /* 节点 B/C 暂不监控远程节点，保留空配置。 */
    .x1016_consumerHeartbeatTime = {
        0x00000000U, /* B/C 不启用监控项 1。 */
        0x00000000U, /* B/C 不启用监控项 2。 */
        0x00000000U, /* B/C 不启用监控项 3。 */
        0x00000000U, /* B/C 不启用监控项 4。 */
        0x00000000U, /* B/C 不启用监控项 5。 */
        0x00000000U, /* B/C 不启用监控项 6。 */
        0x00000000U, /* B/C 不启用监控项 7。 */
        0x00000000U  /* B/C 不启用监控项 8。 */
    },
#endif
    /* 设置生产者 Heartbeat 周期为 1000 ms。 */
    .x1017_producerHeartbeatTime = CANOPEN_HEARTBEAT_PRODUCER_PERIOD_MS,
    .x1018_identity = {
        .highestSub_indexSupported = 0x04,
        .vendor_ID = 0x00000000,
        .productCode = 0x00000000,
        .revisionNumber = 0x00000000,
        .serialNumber = 0x00000000
    },
    .x1019_synchronousCounterOverflowValue = 0x00,
    .x1280_SDOClientParameter = {
        .highestSub_indexSupported = 0x03,
        .COB_IDClientToServerTx = 0x80000000,
        .COB_IDServerToClientRx = 0x80000000,
        .node_IDOfTheSDOServer = 0x01
    },
    .x1400_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
        /* 启用 RPDO1，并使用默认基准 COB-ID 0x200 加节点号。 */
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_A)
        /* A 节点 RPDO1 接收 C 节点 TPDO1 的 COB-ID 0x183。 */
        .COB_IDUsedByRPDO = 0x00000183,
#else
        .COB_IDUsedByRPDO = 0x00000200,
#endif
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1401_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_A)
        /* A 节点 RPDO2 接收 C 节点 TPDO2 的 COB-ID 0x283。 */
        .COB_IDUsedByRPDO = 0x00000283,
#else
        .COB_IDUsedByRPDO = 0x80000300,
#endif
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1402_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_A)
        /* A 节点 RPDO3 接收 B 节点加速度 TPDO1 的 COB-ID 0x182。 */
        .COB_IDUsedByRPDO = 0x00000182,
#else
        .COB_IDUsedByRPDO = 0x80000400,
#endif
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1403_RPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x05,
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_A)
        /* A 节点 RPDO4 接收 B 节点角速度 TPDO2 的 COB-ID 0x282。 */
        .COB_IDUsedByRPDO = 0x00000282,
#elif (CAN_NODE_ROLE == CAN_NODE_ROLE_B)
        /* B 节点 RPDO4 接收 A 返回的事故 ACK，COB-ID 固定为 0x502。 */
        .COB_IDUsedByRPDO = 0x00000502,
#else
        .COB_IDUsedByRPDO = 0x80000500,
#endif
        .transmissionType = 0xFE,
        .eventTimer = 0x0000
    },
    .x1600_RPDOMappingParameter = {
        /* 将 RPDO1 映射为一个 8 位的 0x2001:00 控制命令。 */
 #if (CAN_NODE_ROLE == CAN_NODE_ROLE_A)
        /* A 节点 RPDO1 映射纬度和经度。 */
        .numberOfMappedApplicationObjectsInPDO = 0x02,
        .applicationObject1 = 0x21000020,
        .applicationObject2 = 0x21010020,
 #else
        .numberOfMappedApplicationObjectsInPDO = 0x01,
        .applicationObject1 = 0x20010008,
        .applicationObject2 = 0x00000000,
 #endif
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1601_RPDOMappingParameter = {
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_A)
        /* A 节点 RPDO2 映射海拔、速度、卫星数和定位有效标志。 */
        .numberOfMappedApplicationObjectsInPDO = 0x04,
        .applicationObject1 = 0x21020020,
        .applicationObject2 = 0x21030010,
        .applicationObject3 = 0x21040008,
        .applicationObject4 = 0x21050008,
#else
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
#endif
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1602_RPDOMappingParameter = {
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_A)
        /* A 节点 RPDO3 映射三轴加速度、有效标志和序号。 */
        .numberOfMappedApplicationObjectsInPDO = 0x05,
        .applicationObject1 = 0x21100010,
        .applicationObject2 = 0x21110010,
        .applicationObject3 = 0x21120010,
        .applicationObject4 = 0x21160008,
        .applicationObject5 = 0x21170008,
#else
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
#endif
    },
    .x1603_RPDOMappingParameter = {
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_A)
        /* A 节点 RPDO4 映射三轴角速度和 16 位序号。 */
        .numberOfMappedApplicationObjectsInPDO = 0x04,
        .applicationObject1 = 0x21130010,
        .applicationObject2 = 0x21140010,
        .applicationObject3 = 0x21150010,
        .applicationObject4 = 0x21180010,
#elif (CAN_NODE_ROLE == CAN_NODE_ROLE_B)
        /* B 节点 RPDO4 映射 A 返回的 16 位事故事件编号。 */
        .numberOfMappedApplicationObjectsInPDO = 0x01,
        .applicationObject1 = 0x21220010,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
#else
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
#endif
    },
    .x1800_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        /* 启用 TPDO1，并使用默认基准 COB-ID 0x180 加节点号。 */
        /* B 节点 TPDO1 使用 IMU 加速度帧 COB-ID 0x182。 */
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_B)
        .COB_IDUsedByTPDO = 0x00000180,
#else
        .COB_IDUsedByTPDO = 0x00000180,
#endif
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        /* 设置 TPDO1 的事件周期为 100 ms。 */
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_B)
        /* B 节点加速度 TPDO 周期为 10 ms。 */
        .eventTimer = 0x000A,
#else
        /* 其他节点 TPDO1 周期为 100 ms。 */
        .eventTimer = 0x0064,
#endif
        .SYNCStartValue = 0x00
    },
    .x1801_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_B)
        /* B 节点 TPDO2 使用 IMU 角速度帧 COB-ID 0x282。 */
        .COB_IDUsedByTPDO = 0x00000280,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        /* 设置 IMU 角速度帧周期为 10 ms。 */
        .eventTimer = 0x000A,
#elif (CAN_NODE_ROLE == CAN_NODE_ROLE_C)
        /* C 节点 TPDO2 使用基准 COB-ID 0x280，节点号 3 后得到 0x283。 */
        .COB_IDUsedByTPDO = 0x00000280,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        /* 设置 GNSS 第二帧事件周期为 100 ms。 */
        .eventTimer = 0x0064,
#else
        .COB_IDUsedByTPDO = 0xC0000280,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
#endif
        .SYNCStartValue = 0x00
    },
    .x1802_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_B)
        /* B 节点启用 TPDO3，基准 COB-ID 0x380 加节点号后为 0x382。 */
        .COB_IDUsedByTPDO = 0x00000380,
        /* 使用异步事件驱动方式发送事故 TPDO。 */
        .transmissionType = 0xFE,
        /* 不额外限制事故事件发送抑制时间。 */
        .inhibitTime = 0x0000,
        /* 关闭周期发送，仅由检测器确认事件后显式请求发送。 */
        .eventTimer = 0x0000,
#else
        /* A/C 节点禁用事故 TPDO3。 */
        .COB_IDUsedByTPDO = 0xC0000380,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
#endif
        .SYNCStartValue = 0x00
    },
    .x1803_TPDOCommunicationParameter = {
        .highestSub_indexSupported = 0x06,
        .COB_IDUsedByTPDO = 0xC0000480,
        .transmissionType = 0xFE,
        .inhibitTime = 0x0000,
        .eventTimer = 0x0000,
        .SYNCStartValue = 0x00
    },
    .x1A00_TPDOMappingParameter = {
        /* 将 TPDO1 映射为一个 32 位的 0x2000:00 应用对象。 */
 #if (CAN_NODE_ROLE == CAN_NODE_ROLE_C)
        /* C 节点 TPDO1 映射纬度和经度，各占 32 位。 */
        .numberOfMappedApplicationObjectsInPDO = 0x02,
        .applicationObject1 = 0x21000020,
#elif (CAN_NODE_ROLE == CAN_NODE_ROLE_B)
        /* B 节点 TPDO1 映射三轴加速度、有效标志和序号。 */
        .numberOfMappedApplicationObjectsInPDO = 0x05,
        .applicationObject1 = 0x21100010,
        .applicationObject2 = 0x21110010,
        .applicationObject3 = 0x21120010,
        .applicationObject4 = 0x21160008,
        .applicationObject5 = 0x21170008,
#else
        .numberOfMappedApplicationObjectsInPDO = 0x01,
        .applicationObject1 = 0x20000020,
#endif
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_C)
        .applicationObject2 = 0x21010020,
#elif (CAN_NODE_ROLE != CAN_NODE_ROLE_B)
        .applicationObject2 = 0x00000000,
#endif
#if (CAN_NODE_ROLE != CAN_NODE_ROLE_B)
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
#endif
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A01_TPDOMappingParameter = {
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_C)
        /* C 节点 TPDO2 映射海拔、速度、卫星数和定位有效标志。 */
        .numberOfMappedApplicationObjectsInPDO = 0x04,
        .applicationObject1 = 0x21020020,
#elif (CAN_NODE_ROLE == CAN_NODE_ROLE_B)
        /* B 节点 TPDO2 映射三轴角速度和 16 位序号。 */
        .numberOfMappedApplicationObjectsInPDO = 0x04,
        .applicationObject1 = 0x21130010,
        .applicationObject2 = 0x21140010,
        .applicationObject3 = 0x21150010,
        .applicationObject4 = 0x21180010,
#else
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
#endif
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_C)
        .applicationObject2 = 0x21030010,
        .applicationObject3 = 0x21040008,
        .applicationObject4 = 0x21050008,
#elif (CAN_NODE_ROLE == CAN_NODE_ROLE_B)
        /* B 节点 TPDO2 的其余映射项已在上方定义。 */
#else
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
#endif
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A02_TPDOMappingParameter = {
#if (CAN_NODE_ROLE == CAN_NODE_ROLE_B)
        /* B 节点 TPDO3 映射事故类型、标志、事件号和两个峰值，共 8 字节。 */
        .numberOfMappedApplicationObjectsInPDO = 0x05,
        .applicationObject1 = 0x21200008,
        .applicationObject2 = 0x21210008,
        .applicationObject3 = 0x21220010,
        .applicationObject4 = 0x21230010,
        .applicationObject5 = 0x21240010,
#else
        /* A/C 节点不映射事故 TPDO3。 */
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
#endif
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    },
    .x1A03_TPDOMappingParameter = {
        .numberOfMappedApplicationObjectsInPDO = 0x00,
        .applicationObject1 = 0x00000000,
        .applicationObject2 = 0x00000000,
        .applicationObject3 = 0x00000000,
        .applicationObject4 = 0x00000000,
        .applicationObject5 = 0x00000000,
        .applicationObject6 = 0x00000000,
        .applicationObject7 = 0x00000000,
        .applicationObject8 = 0x00000000
    }
};

OD_ATTR_RAM OD_RAM_t OD_RAM = {
    .x1001_errorRegister = 0x00,
    .x1010_storeParameters_sub0 = 0x04,
    .x1010_storeParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1011_restoreDefaultParameters_sub0 = 0x04,
    .x1011_restoreDefaultParameters = {0x00000001, 0x00000001, 0x00000001, 0x00000001},
    .x1200_SDOServerParameter = {
        .highestSub_indexSupported = 0x02,
        .COB_IDClientToServerRx = 0x00000600,
        .COB_IDServerToClientTx = 0x00000580
    },
    /* 初始化 TPDO1 实验序号为 0。 */
    .x2000_tpdoSequence = 0x00000000,
    /* 初始化 RPDO1 控制命令为 0。 */
    .x2001_rpdoCommand = 0x00,
    /* 初始化 BH-182 纬度对象。 */
    .x2100_latitudeE7 = 0,
    /* 初始化 BH-182 经度对象。 */
    .x2101_longitudeE7 = 0,
    /* 初始化 BH-182 海拔对象。 */
    .x2102_altitudeMm = 0,
    /* 初始化 BH-182 速度对象。 */
    .x2103_speedMmps = 0,
    /* 初始化 BH-182 卫星数对象。 */
    .x2104_satelliteCount = 0,
    /* 初始化 BH-182 定位有效对象。 */
    .x2105_fixValid = 0
    ,/* 初始化 ICM-42688 加速度和角速度对象。 */
    .x2110_accelX = 0,
    .x2111_accelY = 0,
    .x2112_accelZ = 0,
    .x2113_gyroX = 0,
    .x2114_gyroY = 0,
    .x2115_gyroZ = 0,
    .x2116_valid = 0,
    .x2117_tpdo1Sequence = 0,
    /* 初始化 ICM-42688 TPDO2 的 16 位发送序号。 */
    .x2118_tpdo2Sequence = 0,
    /* 初始化事故 TPDO3 的事件类型。 */
    .x2120_accidentType = 0,
    /* 初始化事故 TPDO3 的保留标志。 */
    .x2121_accidentFlags = 0,
    /* 初始化事故 TPDO3 的事件编号。 */
    .x2122_accidentEventId = 0,
    /* 初始化事故 TPDO3 的加速度峰值。 */
    .x2123_peakAccelMg = 0,
    /* 初始化事故 TPDO3 的角速度峰值。 */
    .x2124_peakGyroDps = 0
};



/*******************************************************************************
    All OD objects (constant definitions)
*******************************************************************************/
typedef struct {
    OD_obj_var_t o_1000_deviceType;
    OD_obj_var_t o_1001_errorRegister;
    OD_obj_array_t o_1003_pre_definedErrorField;
    OD_obj_var_t o_1005_COB_ID_SYNCMessage;
    OD_obj_var_t o_1006_communicationCyclePeriod;
    OD_obj_var_t o_1007_synchronousWindowLength;
    OD_obj_array_t o_1010_storeParameters;
    OD_obj_array_t o_1011_restoreDefaultParameters;
    OD_obj_var_t o_1012_COB_IDTimeStampObject;
    OD_obj_var_t o_1014_COB_ID_EMCY;
    OD_obj_var_t o_1015_inhibitTimeEMCY;
    OD_obj_array_t o_1016_consumerHeartbeatTime;
    OD_obj_var_t o_1017_producerHeartbeatTime;
    OD_obj_record_t o_1018_identity[5];
    OD_obj_var_t o_1019_synchronousCounterOverflowValue;
    OD_obj_record_t o_1200_SDOServerParameter[3];
    OD_obj_record_t o_1280_SDOClientParameter[4];
    OD_obj_record_t o_1400_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1401_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1402_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1403_RPDOCommunicationParameter[4];
    OD_obj_record_t o_1600_RPDOMappingParameter[9];
    OD_obj_record_t o_1601_RPDOMappingParameter[9];
    OD_obj_record_t o_1602_RPDOMappingParameter[9];
    OD_obj_record_t o_1603_RPDOMappingParameter[9];
    OD_obj_record_t o_1800_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1801_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1802_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1803_TPDOCommunicationParameter[6];
    OD_obj_record_t o_1A00_TPDOMappingParameter[9];
    OD_obj_record_t o_1A01_TPDOMappingParameter[9];
    OD_obj_record_t o_1A02_TPDOMappingParameter[9];
    OD_obj_record_t o_1A03_TPDOMappingParameter[9];
    /* 定义 0x2000:00 的 32 位应用变量对象。 */
    OD_obj_var_t o_2000_tpdoSequence;
    /* 定义 0x2001:00 的 8 位应用变量对象。 */
    OD_obj_var_t o_2001_rpdoCommand;
    /* 定义 BH-182 纬度对象。 */
    OD_obj_var_t o_2100_latitudeE7;
    /* 定义 BH-182 经度对象。 */
    OD_obj_var_t o_2101_longitudeE7;
    /* 定义 BH-182 海拔对象。 */
    OD_obj_var_t o_2102_altitudeMm;
    /* 定义 BH-182 速度对象。 */
    OD_obj_var_t o_2103_speedMmps;
    /* 定义 BH-182 卫星数对象。 */
    OD_obj_var_t o_2104_satelliteCount;
    /* 定义 BH-182 定位有效对象。 */
    OD_obj_var_t o_2105_fixValid;
    /* 定义 ICM-42688 应用对象。 */
    OD_obj_var_t o_2110_accelX;
    OD_obj_var_t o_2111_accelY;
    OD_obj_var_t o_2112_accelZ;
    OD_obj_var_t o_2113_gyroX;
    OD_obj_var_t o_2114_gyroY;
    OD_obj_var_t o_2115_gyroZ;
    OD_obj_var_t o_2116_valid;
    OD_obj_var_t o_2117_sequence;
    /* 定义 TPDO2 的独立 16 位序号对象。 */
    OD_obj_var_t o_2118_sequence;
    /* 定义事故 TPDO3 的五个应用对象。 */
    OD_obj_var_t o_2120_accidentType;
    OD_obj_var_t o_2121_accidentFlags;
    OD_obj_var_t o_2122_accidentEventId;
    OD_obj_var_t o_2123_peakAccelMg;
    OD_obj_var_t o_2124_peakGyroDps;
} ODObjs_t;

static CO_PROGMEM ODObjs_t ODObjs = {
    .o_1000_deviceType = {
        .dataOrig = &OD_PERSIST_COMM.x1000_deviceType,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataLength = 4
    },
    .o_1001_errorRegister = {
        .dataOrig = &OD_RAM.x1001_errorRegister,
        .attribute = ODA_SDO_R | ODA_TPDO,
        .dataLength = 1
    },
    .o_1003_pre_definedErrorField = {
        .dataOrig0 = NULL,
        .dataOrig = NULL,
        .attribute0 = ODA_SDO_RW,
        .attribute = ODA_SDO_R | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1005_COB_ID_SYNCMessage = {
        .dataOrig = &OD_PERSIST_COMM.x1005_COB_ID_SYNCMessage,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1006_communicationCyclePeriod = {
        .dataOrig = &OD_PERSIST_COMM.x1006_communicationCyclePeriod,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1007_synchronousWindowLength = {
        .dataOrig = &OD_PERSIST_COMM.x1007_synchronousWindowLength,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1010_storeParameters = {
        .dataOrig0 = &OD_RAM.x1010_storeParameters_sub0,
        .dataOrig = &OD_RAM.x1010_storeParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1011_restoreDefaultParameters = {
        .dataOrig0 = &OD_RAM.x1011_restoreDefaultParameters_sub0,
        .dataOrig = &OD_RAM.x1011_restoreDefaultParameters[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1012_COB_IDTimeStampObject = {
        .dataOrig = &OD_PERSIST_COMM.x1012_COB_IDTimeStampObject,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1014_COB_ID_EMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1014_COB_ID_EMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 4
    },
    .o_1015_inhibitTimeEMCY = {
        .dataOrig = &OD_PERSIST_COMM.x1015_inhibitTimeEMCY,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1016_consumerHeartbeatTime = {
        .dataOrig0 = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime_sub0,
        .dataOrig = &OD_PERSIST_COMM.x1016_consumerHeartbeatTime[0],
        .attribute0 = ODA_SDO_R,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataElementLength = 4,
        .dataElementSizeof = sizeof(uint32_t)
    },
    .o_1017_producerHeartbeatTime = {
        .dataOrig = &OD_PERSIST_COMM.x1017_producerHeartbeatTime,
        .attribute = ODA_SDO_RW | ODA_MB,
        .dataLength = 2
    },
    .o_1018_identity = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.vendor_ID,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.productCode,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.revisionNumber,
            .subIndex = 3,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1018_identity.serialNumber,
            .subIndex = 4,
            .attribute = ODA_SDO_R | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1019_synchronousCounterOverflowValue = {
        .dataOrig = &OD_PERSIST_COMM.x1019_synchronousCounterOverflowValue,
        .attribute = ODA_SDO_RW,
        .dataLength = 1
    },
    .o_1200_SDOServerParameter = {
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDClientToServerRx,
            .subIndex = 1,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_RAM.x1200_SDOServerParameter.COB_IDServerToClientTx,
            .subIndex = 2,
            .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1280_SDOClientParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDClientToServerTx,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.COB_IDServerToClientRx,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_TRPDO | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1280_SDOClientParameter.node_IDOfTheSDOServer,
            .subIndex = 3,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1400_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1400_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1401_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1401_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1402_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1402_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1403_RPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.COB_IDUsedByRPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1403_RPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        }
    },
    .o_1600_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1600_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1601_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1601_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1602_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1602_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1603_RPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1603_RPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1800_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1800_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1801_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1801_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1802_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1802_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1803_TPDOCommunicationParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.highestSub_indexSupported,
            .subIndex = 0,
            .attribute = ODA_SDO_R,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.COB_IDUsedByTPDO,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.transmissionType,
            .subIndex = 2,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.inhibitTime,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.eventTimer,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 2
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1803_TPDOCommunicationParameter.SYNCStartValue,
            .subIndex = 6,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        }
    },
    .o_1A00_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A00_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A01_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A01_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A02_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A02_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    .o_1A03_TPDOMappingParameter = {
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.numberOfMappedApplicationObjectsInPDO,
            .subIndex = 0,
            .attribute = ODA_SDO_RW,
            .dataLength = 1
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject1,
            .subIndex = 1,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject2,
            .subIndex = 2,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject3,
            .subIndex = 3,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject4,
            .subIndex = 4,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject5,
            .subIndex = 5,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject6,
            .subIndex = 6,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject7,
            .subIndex = 7,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        },
        {
            .dataOrig = &OD_PERSIST_COMM.x1A03_TPDOMappingParameter.applicationObject8,
            .subIndex = 8,
            .attribute = ODA_SDO_RW | ODA_MB,
            .dataLength = 4
        }
    },
    /* 定义 0x2000:00 为可读写且允许映射到 TPDO 的 32 位变量。 */
    .o_2000_tpdoSequence = {
        .dataOrig = &OD_RAM.x2000_tpdoSequence,
        .attribute = ODA_SDO_RW | ODA_TPDO | ODA_MB,
        .dataLength = 4
    },
    /* 定义 0x2001:00 为可读写且允许映射到 RPDO 的 8 位变量。 */
    .o_2001_rpdoCommand = {
        .dataOrig = &OD_RAM.x2001_rpdoCommand,
        .attribute = ODA_SDO_RW | ODA_RPDO,
        .dataLength = 1
    },
    /* 定义 0x2100:00 为可读且允许映射到 TPDO 的纬度变量。 */
    .o_2100_latitudeE7 = {
        .dataOrig = &OD_RAM.x2100_latitudeE7,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    /* 定义 0x2101:00 为可读且允许映射到 TPDO 的经度变量。 */
    .o_2101_longitudeE7 = {
        .dataOrig = &OD_RAM.x2101_longitudeE7,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    /* 定义 0x2102:00 为可读且允许映射到 TPDO 的海拔变量。 */
    .o_2102_altitudeMm = {
        .dataOrig = &OD_RAM.x2102_altitudeMm,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 4
    },
    /* 定义 0x2103:00 为可读且允许映射到 TPDO 的速度变量。 */
    .o_2103_speedMmps = {
        .dataOrig = &OD_RAM.x2103_speedMmps,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    /* 定义 0x2104:00 为可读且允许映射到 TPDO 的卫星数变量。 */
    .o_2104_satelliteCount = {
        .dataOrig = &OD_RAM.x2104_satelliteCount,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 1
    },
    /* 定义 0x2105:00 为可读且允许映射到 TPDO 的定位有效变量。 */
    .o_2105_fixValid = {
        .dataOrig = &OD_RAM.x2105_fixValid,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 1
    },
    /* 定义 0x2110:00 为可收发 PDO 的 X 轴加速度变量。 */
    .o_2110_accelX = {
        .dataOrig = &OD_RAM.x2110_accelX,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    /* 定义 0x2111:00 为可收发 PDO 的 Y 轴加速度变量。 */
    .o_2111_accelY = {
        .dataOrig = &OD_RAM.x2111_accelY,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    /* 定义 0x2112:00 为可收发 PDO 的 Z 轴加速度变量。 */
    .o_2112_accelZ = {
        .dataOrig = &OD_RAM.x2112_accelZ,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    /* 定义 0x2113:00 为可收发 PDO 的 X 轴角速度变量。 */
    .o_2113_gyroX = {
        .dataOrig = &OD_RAM.x2113_gyroX,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    /* 定义 0x2114:00 为可收发 PDO 的 Y 轴角速度变量。 */
    .o_2114_gyroY = {
        .dataOrig = &OD_RAM.x2114_gyroY,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    /* 定义 0x2115:00 为可收发 PDO 的 Z 轴角速度变量。 */
    .o_2115_gyroZ = {
        .dataOrig = &OD_RAM.x2115_gyroZ,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    /* 定义 0x2116:00 为可收发 PDO 的 IMU 有效标志。 */
    .o_2116_valid = {
        .dataOrig = &OD_RAM.x2116_valid,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 1
    },
    /* 定义 0x2117:00 为可收发 PDO 的 TPDO1 发送序号。 */
    .o_2117_sequence = {
        .dataOrig = &OD_RAM.x2117_tpdo1Sequence,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 1
    },
    /* 定义 0x2118:00 为可收发 PDO 的 TPDO2 发送序号。 */
    .o_2118_sequence = {
        .dataOrig = &OD_RAM.x2118_tpdo2Sequence,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_RPDO | ODA_MB,
        .dataLength = 2
    },
    /* 定义事故类型对象 0x2120:00。 */
    .o_2120_accidentType = {
        .dataOrig = &OD_RAM.x2120_accidentType,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 1
    },
    /* 定义事故保留标志对象 0x2121:00。 */
    .o_2121_accidentFlags = {
        .dataOrig = &OD_RAM.x2121_accidentFlags,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 1
    },
    /* 定义事故事件编号对象 0x2122:00。 */
    .o_2122_accidentEventId = {
        .dataOrig = &OD_RAM.x2122_accidentEventId,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    /* 定义事故加速度峰值对象 0x2123:00。 */
    .o_2123_peakAccelMg = {
        .dataOrig = &OD_RAM.x2123_peakAccelMg,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    },
    /* 定义事故角速度峰值对象 0x2124:00。 */
    .o_2124_peakGyroDps = {
        .dataOrig = &OD_RAM.x2124_peakGyroDps,
        .attribute = ODA_SDO_R | ODA_TPDO | ODA_MB,
        .dataLength = 2
    }
};


/*******************************************************************************
    Object dictionary
*******************************************************************************/
static OD_ATTR_OD OD_entry_t ODList[] = {
    {0x1000, 0x01, ODT_VAR, &ODObjs.o_1000_deviceType, NULL},
    {0x1001, 0x01, ODT_VAR, &ODObjs.o_1001_errorRegister, NULL},
    {0x1003, 0x11, ODT_ARR, &ODObjs.o_1003_pre_definedErrorField, NULL},
    {0x1005, 0x01, ODT_VAR, &ODObjs.o_1005_COB_ID_SYNCMessage, NULL},
    {0x1006, 0x01, ODT_VAR, &ODObjs.o_1006_communicationCyclePeriod, NULL},
    {0x1007, 0x01, ODT_VAR, &ODObjs.o_1007_synchronousWindowLength, NULL},
    {0x1010, 0x05, ODT_ARR, &ODObjs.o_1010_storeParameters, NULL},
    {0x1011, 0x05, ODT_ARR, &ODObjs.o_1011_restoreDefaultParameters, NULL},
    {0x1012, 0x01, ODT_VAR, &ODObjs.o_1012_COB_IDTimeStampObject, NULL},
    {0x1014, 0x01, ODT_VAR, &ODObjs.o_1014_COB_ID_EMCY, NULL},
    {0x1015, 0x01, ODT_VAR, &ODObjs.o_1015_inhibitTimeEMCY, NULL},
    {0x1016, 0x09, ODT_ARR, &ODObjs.o_1016_consumerHeartbeatTime, NULL},
    {0x1017, 0x01, ODT_VAR, &ODObjs.o_1017_producerHeartbeatTime, NULL},
    {0x1018, 0x05, ODT_REC, &ODObjs.o_1018_identity, NULL},
    {0x1019, 0x01, ODT_VAR, &ODObjs.o_1019_synchronousCounterOverflowValue, NULL},
    {0x1200, 0x03, ODT_REC, &ODObjs.o_1200_SDOServerParameter, NULL},
    {0x1280, 0x04, ODT_REC, &ODObjs.o_1280_SDOClientParameter, NULL},
    {0x1400, 0x04, ODT_REC, &ODObjs.o_1400_RPDOCommunicationParameter, NULL},
    {0x1401, 0x04, ODT_REC, &ODObjs.o_1401_RPDOCommunicationParameter, NULL},
    {0x1402, 0x04, ODT_REC, &ODObjs.o_1402_RPDOCommunicationParameter, NULL},
    {0x1403, 0x04, ODT_REC, &ODObjs.o_1403_RPDOCommunicationParameter, NULL},
    {0x1600, 0x09, ODT_REC, &ODObjs.o_1600_RPDOMappingParameter, NULL},
    {0x1601, 0x09, ODT_REC, &ODObjs.o_1601_RPDOMappingParameter, NULL},
    {0x1602, 0x09, ODT_REC, &ODObjs.o_1602_RPDOMappingParameter, NULL},
    {0x1603, 0x09, ODT_REC, &ODObjs.o_1603_RPDOMappingParameter, NULL},
    {0x1800, 0x06, ODT_REC, &ODObjs.o_1800_TPDOCommunicationParameter, NULL},
    {0x1801, 0x06, ODT_REC, &ODObjs.o_1801_TPDOCommunicationParameter, NULL},
    {0x1802, 0x06, ODT_REC, &ODObjs.o_1802_TPDOCommunicationParameter, NULL},
    {0x1803, 0x06, ODT_REC, &ODObjs.o_1803_TPDOCommunicationParameter, NULL},
    {0x1A00, 0x09, ODT_REC, &ODObjs.o_1A00_TPDOMappingParameter, NULL},
    {0x1A01, 0x09, ODT_REC, &ODObjs.o_1A01_TPDOMappingParameter, NULL},
    {0x1A02, 0x09, ODT_REC, &ODObjs.o_1A02_TPDOMappingParameter, NULL},
    {0x1A03, 0x09, ODT_REC, &ODObjs.o_1A03_TPDOMappingParameter, NULL},
    /* 添加 TPDO 实验应用对象 0x2000:00。 */
    {0x2000, 0x01, ODT_VAR, &ODObjs.o_2000_tpdoSequence, NULL},
    /* 添加 RPDO 实验应用对象 0x2001:00。 */
    {0x2001, 0x01, ODT_VAR, &ODObjs.o_2001_rpdoCommand, NULL},
    /* 添加 BH-182 纬度对象 0x2100:00。 */
    {0x2100, 0x01, ODT_VAR, &ODObjs.o_2100_latitudeE7, NULL},
    /* 添加 BH-182 经度对象 0x2101:00。 */
    {0x2101, 0x01, ODT_VAR, &ODObjs.o_2101_longitudeE7, NULL},
    /* 添加 BH-182 海拔对象 0x2102:00。 */
    {0x2102, 0x01, ODT_VAR, &ODObjs.o_2102_altitudeMm, NULL},
    /* 添加 BH-182 速度对象 0x2103:00。 */
    {0x2103, 0x01, ODT_VAR, &ODObjs.o_2103_speedMmps, NULL},
    /* 添加 BH-182 卫星数对象 0x2104:00。 */
    {0x2104, 0x01, ODT_VAR, &ODObjs.o_2104_satelliteCount, NULL},
    /* 添加 BH-182 定位有效对象 0x2105:00。 */
    {0x2105, 0x01, ODT_VAR, &ODObjs.o_2105_fixValid, NULL},
    /* 添加 ICM-42688 X 轴加速度对象 0x2110:00。 */
    {0x2110, 0x01, ODT_VAR, &ODObjs.o_2110_accelX, NULL},
    /* 添加 ICM-42688 Y 轴加速度对象 0x2111:00。 */
    {0x2111, 0x01, ODT_VAR, &ODObjs.o_2111_accelY, NULL},
    /* 添加 ICM-42688 Z 轴加速度对象 0x2112:00。 */
    {0x2112, 0x01, ODT_VAR, &ODObjs.o_2112_accelZ, NULL},
    /* 添加 ICM-42688 X 轴角速度对象 0x2113:00。 */
    {0x2113, 0x01, ODT_VAR, &ODObjs.o_2113_gyroX, NULL},
    /* 添加 ICM-42688 Y 轴角速度对象 0x2114:00。 */
    {0x2114, 0x01, ODT_VAR, &ODObjs.o_2114_gyroY, NULL},
    /* 添加 ICM-42688 Z 轴角速度对象 0x2115:00。 */
    {0x2115, 0x01, ODT_VAR, &ODObjs.o_2115_gyroZ, NULL},
    /* 添加 ICM-42688 有效标志对象 0x2116:00。 */
    {0x2116, 0x01, ODT_VAR, &ODObjs.o_2116_valid, NULL},
    /* 添加 ICM-42688 TPDO1 发送序号对象 0x2117:00。 */
    {0x2117, 0x01, ODT_VAR, &ODObjs.o_2117_sequence, NULL},
    /* 添加 ICM-42688 TPDO2 发送序号对象 0x2118:00。 */
    {0x2118, 0x01, ODT_VAR, &ODObjs.o_2118_sequence, NULL},
    /* 添加事故类型对象 0x2120:00。 */
    {0x2120, 0x01, ODT_VAR, &ODObjs.o_2120_accidentType, NULL},
    /* 添加事故标志对象 0x2121:00。 */
    {0x2121, 0x01, ODT_VAR, &ODObjs.o_2121_accidentFlags, NULL},
    /* 添加事故事件编号对象 0x2122:00。 */
    {0x2122, 0x01, ODT_VAR, &ODObjs.o_2122_accidentEventId, NULL},
    /* 添加事故加速度峰值对象 0x2123:00。 */
    {0x2123, 0x01, ODT_VAR, &ODObjs.o_2123_peakAccelMg, NULL},
    /* 添加事故角速度峰值对象 0x2124:00。 */
    {0x2124, 0x01, ODT_VAR, &ODObjs.o_2124_peakGyroDps, NULL},
    {0x0000, 0x00, 0, NULL, NULL}
};

static OD_t _OD = {
    (sizeof(ODList) / sizeof(ODList[0])) - 1,
    &ODList[0]
};

OD_t *OD = &_OD;
