#ifndef CANOPEN_NODE_CONFIG_H
#define CANOPEN_NODE_CONFIG_H

#include <stdint.h>

#define CAN_NODE_ROLE_A 0U
#define CAN_NODE_ROLE_B 1U
#define CAN_NODE_ROLE_C 2U

#define CANOPEN_HEARTBEAT_PRODUCER_PERIOD_MS 1000U
#define CANOPEN_HEARTBEAT_CONSUMER_TIMEOUT_MS 1500U
#define CANOPEN_HEALTH_TIMEOUT_EPISODE_LIMIT 3U
#define CANOPEN_HEALTH_RECOVERY_TIMEOUT_MS 5000U
#define CANOPEN_HEALTH_STABLE_TIME_MS 2000U
#define CANOPEN_IMU_PDO_TIMEOUT_MS 30U
#define CANOPEN_GNSS_PDO_TIMEOUT_MS 300U
#define CANOPEN_ACCIDENT_ACK_TIMEOUT_MS 500U
#define CANOPEN_ACCIDENT_ACK_RETRY_WARNING_LIMIT 10U
#define CANOPEN_ACCIDENT_ACK_DEGRADED_RETRY_MS 5000U
#define CANOPEN_ACCIDENT_ACCEL_UNIT_MG 100U
#define CANOPEN_ACCIDENT_GYRO_UNIT_DPS 10U
#define CANOPEN_HEARTBEAT_CONSUMER_ENTRY(node_id, timeout_ms) \
    ((((uint32_t)(node_id)) << 16U) | ((uint32_t)(timeout_ms) & 0xFFFFU)) /* 缁勫悎 Node-ID 鍜岃秴鏃舵椂闂淬€?*/

#if defined(CAN_NODE_BUILD_A)
#define CAN_NODE_ROLE CAN_NODE_ROLE_A
#elif defined(CAN_NODE_BUILD_B)
#define CAN_NODE_ROLE CAN_NODE_ROLE_B
#elif defined(CAN_NODE_BUILD_C)
#define CAN_NODE_ROLE CAN_NODE_ROLE_C
#elif !defined(CAN_NODE_ROLE)
#error "Define CAN_NODE_BUILD_A, CAN_NODE_BUILD_B, or CAN_NODE_BUILD_C"
#endif

#if (CAN_NODE_ROLE == CAN_NODE_ROLE_A)
#define CANOPEN_NODE_ID 1U
#elif (CAN_NODE_ROLE == CAN_NODE_ROLE_B)
#define CANOPEN_NODE_ID 2U
#elif (CAN_NODE_ROLE == CAN_NODE_ROLE_C)
#define CANOPEN_NODE_ID 3U
#else
#error "CAN_NODE_ROLE 蹇呴』璁剧疆涓?CAN_NODE_ROLE_A銆丆AN_NODE_ROLE_B 鎴?CAN_NODE_ROLE_C"
#endif

#endif /* CANOPEN_NODE_CONFIG_H */
