#ifndef ESP32_MQTT_CONFIG_H
#define ESP32_MQTT_CONFIG_H

#define ESP32_MQTT_CONFIGURED 0U

#define ESP32_WIFI_SSID "YOUR_WIFI_SSID"
#define ESP32_WIFI_PASSWORD "YOUR_WIFI_PASSWORD"

#define ESP32_MQTT_HOST "YOUR_ONENET_MQTT_HOST"
#define ESP32_MQTT_TLS_ENABLED 1U
#define ESP32_MQTT_TLS_VERIFY_SERVER 0U
#if (ESP32_MQTT_TLS_ENABLED != 0U)
  #if (ESP32_MQTT_TLS_VERIFY_SERVER != 0U)
    #define ESP32_MQTT_SCHEME 3U
  #else
    #define ESP32_MQTT_SCHEME 2U
  #endif
  #define ESP32_MQTT_PORT 8883U
#else
  #define ESP32_MQTT_SCHEME 1U
  #define ESP32_MQTT_PORT 1883U
#endif
#define ESP32_MQTT_CLIENT_ID "YOUR_CLIENT_ID"
#define ESP32_MQTT_USERNAME "YOUR_USERNAME"
#define ESP32_MQTT_PASSWORD "YOUR_MQTT_PASSWORD"
#define ESP32_MQTT_PUB_TOPIC "YOUR_PUBLISH_TOPIC"
#define ESP32_MQTT_SUB_TOPIC "YOUR_SUBSCRIBE_TOPIC"
#define ESP32_MQTT_ACK_TOPIC "YOUR_ACK_TOPIC"
#define ESP32_MQTT_ACCIDENT_TOPIC "YOUR_ACCIDENT_TOPIC"

#define ESP32_MQTT_KEEPALIVE_SEC 60U
#define ESP32_MQTT_PUBLISH_PERIOD_MS 1000U
#define ESP32_MQTT_RETRY_PERIOD_MS 5000U
#define ESP32_IWDG_TIMEOUT_MS 8000U
#define ESP32_IWDG_REFRESH_PERIOD_MS 500U

#endif /* ESP32_MQTT_CONFIG_H */
